Eigenvalues for L=5


k=1

In [2]:
import numpy as np

# Initialize the Hamiltonian matrix
H = np.zeros((5, 5))

# Define the values based on the absolute difference between row and column indices
for m in range(5):
    for n in range(5):
        diff = abs(m - n)
        if diff == 0:
            H[m, n] = 295 / 56
        elif diff == 1:
            H[m, n] = -356 / 105
        elif diff == 2:
            H[m, n] = 92 / 105
        elif diff == 3:
            H[m, n] = -4 / 35
        elif diff == 4:
            H[m, n] = -3 / 560

# Multiply every element by 32
H *= 2

print(H)


# Diagonalize the Hamiltonian matrix
eigenvalues, eigenvectors = np.linalg.eigh(H)

# Find the index of the lowest eigenvalue
min_index = np.argmin(eigenvalues)

# Print the lowest eigenvalue
print("Lowest Eigenvalue: ", eigenvalues[min_index])

# Print the eigenvector corresponding to the lowest eigenvalue with commas
print("Eigenvector corresponding to the lowest eigenvalue: ", ', '.join(map(str, eigenvectors[:, min_index])))



[[10.53571429 -6.78095238  1.75238095 -0.22857143 -0.01071429]
 [-6.78095238 10.53571429 -6.78095238  1.75238095 -0.22857143]
 [ 1.75238095 -6.78095238 10.53571429 -6.78095238  1.75238095]
 [-0.22857143  1.75238095 -6.78095238 10.53571429 -6.78095238]
 [-0.01071429 -0.22857143  1.75238095 -6.78095238 10.53571429]]
Lowest Eigenvalue:  0.6721047093911651
Eigenvector corresponding to the lowest eigenvalue:  -0.25134407243985873, -0.5043293090198548, -0.6041160572487743, -0.5043293090198556, -0.2513440724398592


k=2

In [3]:
import numpy as np

# Initialize the Hamiltonian matrix
H = np.zeros((15, 15))

# Define the values based on the absolute difference between row and column indices
for m in range(15):
    for n in range(15):
        diff = abs(m - n)
        if diff == 0:
            H[m, n] = 295 / 56
        elif diff == 1:
            H[m, n] = -356 / 105
        elif diff == 2:
            H[m, n] = 92 / 105
        elif diff == 3:
            H[m, n] = -4 / 35
        elif diff == 4:
            H[m, n] = -3 / 560

# Multiply every element by 32
H *= 8

print(H)


# Diagonalize the Hamiltonian matrix
eigenvalues, eigenvectors = np.linalg.eigh(H)

# Find the index of the lowest eigenvalue
min_index = np.argmin(eigenvalues)

# Print the lowest eigenvalue
print("Lowest Eigenvalue: ", eigenvalues[min_index])

# Print the eigenvector corresponding to the lowest eigenvalue with commas
print("Eigenvector corresponding to the lowest eigenvalue: ", ', '.join(map(str, eigenvectors[:, min_index])))



[[ 42.14285714 -27.12380952   7.00952381  -0.91428571  -0.04285714
    0.           0.           0.           0.           0.
    0.           0.           0.           0.           0.        ]
 [-27.12380952  42.14285714 -27.12380952   7.00952381  -0.91428571
   -0.04285714   0.           0.           0.           0.
    0.           0.           0.           0.           0.        ]
 [  7.00952381 -27.12380952  42.14285714 -27.12380952   7.00952381
   -0.91428571  -0.04285714   0.           0.           0.
    0.           0.           0.           0.           0.        ]
 [ -0.91428571   7.00952381 -27.12380952  42.14285714 -27.12380952
    7.00952381  -0.91428571  -0.04285714   0.           0.
    0.           0.           0.           0.           0.        ]
 [ -0.04285714  -0.91428571   7.00952381 -27.12380952  42.14285714
  -27.12380952   7.00952381  -0.91428571  -0.04285714   0.
    0.           0.           0.           0.           0.        ]
 [  0.          -0.04285714  -

k=3

In [4]:
import numpy as np

# Initialize the Hamiltonian matrix
H = np.zeros((35, 35))

# Define the values based on the absolute difference between row and column indices
for m in range(35):
    for n in range(35):
        diff = abs(m - n)
        if diff == 0:
            H[m, n] = 295 / 56
        elif diff == 1:
            H[m, n] = -356 / 105
        elif diff == 2:
            H[m, n] = 92 / 105
        elif diff == 3:
            H[m, n] = -4 / 35
        elif diff == 4:
            H[m, n] = -3 / 560

# Multiply every element by 32
H *= 32

print(H)


# Diagonalize the Hamiltonian matrix
eigenvalues, eigenvectors = np.linalg.eigh(H)

# Find the index of the lowest eigenvalue
min_index = np.argmin(eigenvalues)

# Print the lowest eigenvalue
print("Lowest Eigenvalue: ", eigenvalues[min_index])

# Print the eigenvector corresponding to the lowest eigenvalue with commas
print("Eigenvector corresponding to the lowest eigenvalue: ", ', '.join(map(str, eigenvectors[:, min_index])))



[[ 168.57142857 -108.4952381    28.03809524 ...    0.
     0.            0.        ]
 [-108.4952381   168.57142857 -108.4952381  ...    0.
     0.            0.        ]
 [  28.03809524 -108.4952381   168.57142857 ...    0.
     0.            0.        ]
 ...
 [   0.            0.            0.         ...  168.57142857
  -108.4952381    28.03809524]
 [   0.            0.            0.         ... -108.4952381
   168.57142857 -108.4952381 ]
 [   0.            0.            0.         ...   28.03809524
  -108.4952381   168.57142857]]
Lowest Eigenvalue:  0.2503322630584288
Eigenvector corresponding to the lowest eigenvalue:  -0.01562439794447787, -0.036253739341118266, -0.05718354867237093, -0.07745098717392918, -0.09698598421067672, -0.11573451763181072, -0.13357856583741703, -0.1503807953839857, -0.16600826142011724, -0.18033803400972662, -0.19325794339625801, -0.2046669963426956, -0.21447601606894154, -0.22260832334410513, -0.22900034255806578, -0.23360210248252816, -0.236377627743274

k=4

In [5]:
import numpy as np

# Initialize the Hamiltonian matrix
H = np.zeros((75, 75))

# Define the values based on the absolute difference between row and column indices
for m in range(75):
    for n in range(75):
        diff = abs(m - n)
        if diff == 0:
            H[m, n] = 295 / 56
        elif diff == 1:
            H[m, n] = -356 / 105
        elif diff == 2:
            H[m, n] = 92 / 105
        elif diff == 3:
            H[m, n] = -4 / 35
        elif diff == 4:
            H[m, n] = -3 / 560

# Multiply every element by 32
H *= 128

print(H)


# Diagonalize the Hamiltonian matrix
eigenvalues, eigenvectors = np.linalg.eigh(H)

# Find the index of the lowest eigenvalue
min_index = np.argmin(eigenvalues)

# Print the lowest eigenvalue
print("Lowest Eigenvalue: ", eigenvalues[min_index])

# Print the eigenvector corresponding to the lowest eigenvalue with commas
print("Eigenvector corresponding to the lowest eigenvalue: ", ', '.join(map(str, eigenvectors[:, min_index])))



[[ 674.28571429 -433.98095238  112.15238095 ...    0.
     0.            0.        ]
 [-433.98095238  674.28571429 -433.98095238 ...    0.
     0.            0.        ]
 [ 112.15238095 -433.98095238  674.28571429 ...    0.
     0.            0.        ]
 ...
 [   0.            0.            0.         ...  674.28571429
  -433.98095238  112.15238095]
 [   0.            0.            0.         ... -433.98095238
   674.28571429 -433.98095238]
 [   0.            0.            0.         ...  112.15238095
  -433.98095238  674.28571429]]
Lowest Eigenvalue:  0.22149846328336795
Eigenvector corresponding to the lowest eigenvalue:  0.005044562876055658, 0.011735208884293238, 0.018593243860403195, 0.025349166135936192, 0.03202014713129138, 0.038626615792177355, 0.04516636410416874, 0.05162876558407795, 0.05800212041900192, 0.06427515536924347, 0.07043697054130703, 0.07647690841496682, 0.08238452384988544, 0.08814959703487525, 0.09376215334538737, 0.0992124818199786, 0.1044911522240447, 0.10958

k=5

In [6]:
import numpy as np

# Initialize the Hamiltonian matrix
H = np.zeros((155, 155))

# Define the values based on the absolute difference between row and column indices
for m in range(155):
    for n in range(155):
        diff = abs(m - n)
        if diff == 0:
            H[m, n] = 295 / 56
        elif diff == 1:
            H[m, n] = -356 / 105
        elif diff == 2:
            H[m, n] = 92 / 105
        elif diff == 3:
            H[m, n] = -4 / 35
        elif diff == 4:
            H[m, n] = -3 / 560

# Multiply every element by 32
H *= 512

print(H)


# Diagonalize the Hamiltonian matrix
eigenvalues, eigenvectors = np.linalg.eigh(H)

# Find the index of the lowest eigenvalue
min_index = np.argmin(eigenvalues)

# Print the lowest eigenvalue
print("Lowest Eigenvalue: ", eigenvalues[min_index])

# Print the eigenvector corresponding to the lowest eigenvalue with commas
print("Eigenvector corresponding to the lowest eigenvalue: ", ', '.join(map(str, eigenvectors[:, min_index])))



[[ 2697.14285714 -1735.92380952   448.60952381 ...     0.
      0.             0.        ]
 [-1735.92380952  2697.14285714 -1735.92380952 ...     0.
      0.             0.        ]
 [  448.60952381 -1735.92380952  2697.14285714 ...     0.
      0.             0.        ]
 ...
 [    0.             0.             0.         ...  2697.14285714
  -1735.92380952   448.60952381]
 [    0.             0.             0.         ... -1735.92380952
   2697.14285714 -1735.92380952]
 [    0.             0.             0.         ...   448.60952381
  -1735.92380952  2697.14285714]]
Lowest Eigenvalue:  0.2089237222534087
Eigenvector corresponding to the lowest eigenvalue:  -0.0017074049254533305, -0.003974167298013526, -0.006302774691059165, -0.008605106215475535, -0.010890014855650172, -0.013167397102463209, -0.01543944554931554, -0.017705465388003383, -0.019964356103788862, -0.022215112635389715, -0.024456800940875788, -0.026688507582845834, -0.0289093236986373, -0.03111834364202548, -0.0333146660

k=10

In [7]:
import numpy as np

# Initialize the Hamiltonian matrix
H = np.zeros((5115, 5115))

# Define the values based on the absolute difference between row and column indices
for m in range(5115):
    for n in range(5115):
        diff = abs(m - n)
        if diff == 0:
            H[m, n] = 295 / 56
        elif diff == 1:
            H[m, n] = -356 / 105
        elif diff == 2:
            H[m, n] = 92 / 105
        elif diff == 3:
            H[m, n] = -4 / 35
        elif diff == 4:
            H[m, n] = -3 / 560

# Multiply every element by 32
H *= 524288

print(H)


# Diagonalize the Hamiltonian matrix
eigenvalues, eigenvectors = np.linalg.eigh(H)

# Find the index of the lowest eigenvalue
min_index = np.argmin(eigenvalues)

# Print the lowest eigenvalue
print("Lowest Eigenvalue: ", eigenvalues[min_index])

# Print the eigenvector corresponding to the lowest eigenvalue with commas
print("Eigenvector corresponding to the lowest eigenvalue: ", ', '.join(map(str, eigenvectors[:, min_index])))



[[ 2761874.28571429 -1777585.98095238   459376.15238095 ...
         0.                0.                0.        ]
 [-1777585.98095238  2761874.28571429 -1777585.98095238 ...
         0.                0.                0.        ]
 [  459376.15238095 -1777585.98095238  2761874.28571429 ...
         0.                0.                0.        ]
 ...
 [       0.                0.                0.         ...
   2761874.28571429 -1777585.98095238   459376.15238095]
 [       0.                0.                0.         ...
  -1777585.98095238  2761874.28571429 -1777585.98095238]
 [       0.                0.                0.         ...
    459376.15238095 -1777585.98095238  2761874.28571429]]
Lowest Eigenvalue:  0.1977378384089616
Eigenvector corresponding to the lowest eigenvalue:  -9.051444601529819e-06, -2.107182734549574e-05, -3.342855746799236e-05, -4.565956210237811e-05, -5.781678862702789e-05, -6.995765182351292e-05, -8.209869754993016e-05, -9.4241151297959e-05, -0.0001063